-- Talents 4 · auditoria do contrato Frontend ↔ Supabase.
-- SOMENTE LEITURA: este arquivo não cria, altera ou remove objetos e não lê linhas de negócio.
-- Execute-o no SQL Editor depois de 00_preflight.sql. O resultado é um inventário; não é
-- autorização para executar 10_additive.sql nem para inventar uma migração sem revisar os tipos.
with expected_tables(table_name, feature, security_expected) as (
  values
    ('candidatos', 'Base de Talentos', true),
    ('employers', 'Empregadores', true),
    ('employer_openings', 'Vagas e oportunidades', true),
    ('talent_opportunity_matches', 'Seleções modernas', true),
    ('candidate_employer_matches', 'Seleções legadas lidas para compatibilidade', true),
    ('candidate_employer_links', 'Vínculos legados lidos para compatibilidade', true),
    ('talent_mapping_profiles', 'Perfis do mapeamento', true),
    ('talent_mapping_items', 'Linhas do mapeamento', true),
    ('talent_mapping_partners', 'Parceiros NectaNet', true),
    ('organizational_plan_entries', 'Planejamento organizacional', true),
    ('organizational_meetings', 'Reuniões organizacionais', true),
    ('organizational_weekly_summaries', 'Resumos semanais', true),
    ('organizational_replacement_requests', 'Reposições organizacionais', true),
    ('operational_tasks', 'Tarefas operacionais', true),
    ('operational_metrics', 'Métricas operacionais', true),
    ('org_ui_state_snapshots', 'Acervo preservado', true),
    ('crm_activities', 'Agenda e atividades', true),
    ('contact_records', 'Contatos', true),
    ('contact_categories', 'Categorias de contatos', true),
    ('contact_record_categories', 'Categorias por contato', true),
    ('contact_relationships', 'Relacionamentos de contatos', true),
    ('contact_interactions', 'Interações de contatos', true),
    ('contact_followups', 'Follow-ups de contatos', true),
    ('german_course_classes', 'Turmas de alemão', true),
    ('german_course_enrollments', 'Matrículas de alemão', true),
    ('german_course_updates', 'Atualizações de alemão', true),
    ('usuarios', 'Perfis internos e autorização', true)
), expected_columns(table_name, column_name, criticality, accepted_types, source) as (
  values
    -- Base canônica de Talentos. A lista reúne SELECTS, formulário, detalhe e PDF.
    ('candidatos','id','OBRIGATORIA',array['text','character varying','uuid'],'SELECTS.candidates'),
    ('candidatos','nome_completo','OBRIGATORIA',array['text','character varying'],'SELECTS.candidates'),
    ('candidatos','ativo','OBRIGATORIA',array['boolean','text','character varying'],'SELECTS.candidates'),
    ('candidatos','status_pipeline','OBRIGATORIA',array['text','character varying'],'SELECTS.candidates'),
    ('candidatos','ultima_atualizacao','OBRIGATORIA',array['timestamp with time zone','timestamp without time zone','date'],'SELECTS.candidates'),
    ('candidatos','email','FUNCIONAL',array[]::text[],'SELECTS.candidates/BASIC_FIELDS'),
    ('candidatos','telefone','FUNCIONAL',array[]::text[],'SELECTS.candidates/BASIC_FIELDS'),
    ('candidatos','cidade_atual','FUNCIONAL',array[]::text[],'SELECTS.candidates/BASIC_FIELDS'),
    ('candidatos','pais_de_origem','FUNCIONAL',array[]::text[],'SELECTS.candidates/BASIC_FIELDS'),
    ('candidatos','idade','FUNCIONAL',array['integer','numeric','text','character varying'],'SELECTS.candidates/BASIC_FIELDS'),
    ('candidatos','substatus','FUNCIONAL',array[]::text[],'SELECTS.candidates'),
    ('candidatos','status_final','FUNCIONAL',array[]::text[],'SELECTS.candidates'),
    ('candidatos','data_da_candidatura','FUNCIONAL',array['date','timestamp with time zone','timestamp without time zone','text'],'SELECTS.candidates'),
    ('candidatos','data_entrada_etapa_atual','FUNCIONAL',array['date','timestamp with time zone','timestamp without time zone','text'],'SELECTS.candidates'),
    ('candidatos','responsavel_interno','FUNCIONAL',array[]::text[],'SELECTS.candidates/BASIC_FIELDS'),
    ('candidatos','prioridade_comercial','FUNCIONAL',array[]::text[],'SELECTS.candidates/BASIC_FIELDS'),
    ('candidatos','perfil','FUNCIONAL',array[]::text[],'SELECTS.candidates'),
    ('candidatos','nivel_alemao','FUNCIONAL',array[]::text[],'SELECTS.candidates/BASIC_FIELDS'),
    ('candidatos','em_curso_de_alemao','FUNCIONAL',array[]::text[],'SELECTS.candidates'),
    ('candidatos','nivel_alvo','FUNCIONAL',array[]::text[],'SELECTS.candidates/BASIC_FIELDS'),
    ('candidatos','previsao_termino_alemao','FUNCIONAL',array['date','timestamp with time zone','timestamp without time zone','text'],'SELECTS.candidates/BASIC_FIELDS'),
    ('candidatos','resultado_da_prova','FUNCIONAL',array[]::text[],'SELECTS.candidates/BASIC_FIELDS'),
    ('candidatos','area_profissional','FUNCIONAL',array[]::text[],'SELECTS.candidates/BASIC_FIELDS'),
    ('candidatos','profissao_principal','FUNCIONAL',array[]::text[],'SELECTS.candidates/BASIC_FIELDS'),
    ('candidatos','resumo_rh_curto','FUNCIONAL',array[]::text[],'SELECTS.candidates/BASIC_FIELDS/PDF'),
    ('candidatos','documentacao_completa','FUNCIONAL',array['boolean','text','character varying'],'SELECTS.candidates/BASIC_FIELDS/PDF'),
    ('candidatos','pendencia_documental_critica','FUNCIONAL',array[]::text[],'SELECTS.candidates/BASIC_FIELDS/PDF'),
    ('candidatos','elegivel_para_employer','FUNCIONAL',array['boolean','text','character varying'],'SELECTS.candidates'),
    ('candidatos','pronto_para_employer','FUNCIONAL',array['boolean','text','character varying'],'SELECTS.candidates/BASIC_FIELDS'),
    ('candidatos','readiness_internacional','FUNCIONAL',array[]::text[],'SELECTS.candidates'),
    ('candidatos','risco_desistencia','FUNCIONAL',array[]::text[],'SELECTS.candidates'),
    ('candidatos','disponibilidade_mudanca','FUNCIONAL',array[]::text[],'SELECTS.candidates/BASIC_FIELDS/PDF'),
    ('candidatos','status_employer','FUNCIONAL',array[]::text[],'SELECTS.candidates'),
    ('candidatos','retorno_employer','FUNCIONAL',array[]::text[],'SELECTS.candidates'),
    ('candidatos','data_envio_employer','FUNCIONAL',array['date','timestamp with time zone','timestamp without time zone','text'],'SELECTS.candidates'),
    ('candidatos','motivo_inativacao','FUNCIONAL',array[]::text[],'SELECTS.candidates'),
    ('candidatos','data_inativacao','FUNCIONAL',array['date','timestamp with time zone','timestamp without time zone','text'],'SELECTS.candidates'),
    ('candidatos','reativavel','FUNCIONAL',array['boolean','text','character varying'],'SELECTS.candidates'),
    ('candidatos','tipo_de_candidato','FUNCIONAL',array[]::text[],'SELECTS.candidates'),
    ('candidatos','tipo_vaga_preferido','FUNCIONAL',array[]::text[],'SELECTS.candidates'),
    ('candidatos','cv_drive_web_link','FUNCIONAL',array[]::text[],'SELECTS.candidates/BASIC_FIELDS/PDF'),
    ('candidatos','cv_drive_file_name','FUNCIONAL',array[]::text[],'SELECTS.candidates'),
    ('candidatos','universidade','FUNCIONAL',array[]::text[],'BASIC_FIELDS/PDF'),
    ('candidatos','curso_de_graduacao','FUNCIONAL',array[]::text[],'BASIC_FIELDS/PDF'),
    ('candidatos','posgraduacao','FUNCIONAL',array[]::text[],'BASIC_FIELDS/PDF'),
    ('candidatos','experiencia_profissional_tempo','FUNCIONAL',array[]::text[],'BASIC_FIELDS/PDF'),
    ('candidatos','anabin','FUNCIONAL',array[]::text[],'BASIC_FIELDS/PDF'),
    ('candidatos','perfil_profissional_para_apresentacao','FUNCIONAL',array[]::text[],'BASIC_FIELDS/PDF'),
    ('candidatos','resumo_profissional','FUNCIONAL',array[]::text[],'BASIC_FIELDS/PDF'),
    ('candidatos','relato_sobre_a_experiencia_profissional','FUNCIONAL',array[]::text[],'BASIC_FIELDS/PDF'),
    ('candidatos','lingua_estrangeira','FUNCIONAL',array[]::text[],'BASIC_FIELDS/PDF'),
    ('candidatos','nivel_lingua_estrangeira','FUNCIONAL',array[]::text[],'BASIC_FIELDS/PDF'),
    ('candidatos','instituicao_ensino','FUNCIONAL',array[]::text[],'BASIC_FIELDS'),
    ('candidatos','bolsa_concedida','FUNCIONAL',array[]::text[],'BASIC_FIELDS'),
    ('candidatos','bolsa_percentual','FUNCIONAL',array['numeric','integer','text','character varying'],'BASIC_FIELDS'),
    ('candidatos','observacoes_internas','FUNCIONAL',array[]::text[],'BASIC_FIELDS/PDF'),
    ('candidatos','observacao','FUNCIONAL',array[]::text[],'BASIC_FIELDS'),
    ('candidatos','data_prevista_mudanca','FUNCIONAL',array['date','timestamp with time zone','timestamp without time zone','text'],'BASIC_FIELDS'),
    ('candidatos','passaporte_status','FUNCIONAL',array[]::text[],'BASIC_FIELDS/PDF'),
    ('candidatos','passaporte_numero','FUNCIONAL',array[]::text[],'BASIC_FIELDS'),
    ('candidatos','passaporte_validade','FUNCIONAL',array['date','timestamp with time zone','timestamp without time zone','text'],'BASIC_FIELDS/PDF'),
    ('candidatos','passaporte_arquivo','FUNCIONAL',array[]::text[],'Detalhe de documentos'),
    ('candidatos','cpf','FUNCIONAL',array[]::text[],'Detalhe/PDF'),
    ('candidatos','numero_do_passaporte','FUNCIONAL',array[]::text[],'Detalhe/PDF'),
    ('candidatos','validade_do_passaporte','FUNCIONAL',array['date','timestamp with time zone','timestamp without time zone','text'],'Detalhe/PDF'),
    ('candidatos','diploma_status','FUNCIONAL',array[]::text[],'BASIC_FIELDS/PDF'),
    ('candidatos','diploma','FUNCIONAL',array[]::text[],'Detalhe de documentos'),
    ('candidatos','diploma_arquivo','FUNCIONAL',array[]::text[],'Detalhe de documentos'),
    ('candidatos','historico_status','FUNCIONAL',array[]::text[],'BASIC_FIELDS/PDF'),
    ('candidatos','historico','FUNCIONAL',array[]::text[],'Detalhe de documentos'),
    ('candidatos','historico_arquivo','FUNCIONAL',array[]::text[],'Detalhe de documentos'),
    ('candidatos','registro_status','FUNCIONAL',array[]::text[],'BASIC_FIELDS/PDF'),
    ('candidatos','registro_numero','FUNCIONAL',array[]::text[],'BASIC_FIELDS'),
    ('candidatos','registro_validade','FUNCIONAL',array['date','timestamp with time zone','timestamp without time zone','text'],'BASIC_FIELDS'),
    ('candidatos','registro_arquivo','FUNCIONAL',array[]::text[],'Detalhe de documentos'),
    ('candidatos','etapa_de_saida','FUNCIONAL',array[]::text[],'Detalhe de histórico'),
    ('candidatos','observacao_final_de_saida','FUNCIONAL',array[]::text[],'Fixture/histórico'),
    ('candidatos','historico_operacional','FUNCIONAL',array[]::text[],'Detalhe de histórico'),
    ('candidatos','atualizado_por','FUNCIONAL',array[]::text[],'Fixture/histórico'),

    -- Empregadores e vagas.
    ('employers','id','OBRIGATORIA',array['uuid'],'SELECTS.employers'),
    ('employers','nome','OBRIGATORIA',array[]::text[],'SELECTS.employers/EMPLOYER_FIELDS'),
    ('employers','nome_normalizado','FUNCIONAL',array[]::text[],'SELECTS.employers'),
    ('employers','ativo','FUNCIONAL',array['boolean','text','character varying'],'SELECTS.employers/EMPLOYER_FIELDS'),
    ('employers','tipo','FUNCIONAL',array[]::text[],'SELECTS.employers'),
    ('employers','status','FUNCIONAL',array[]::text[],'SELECTS.employers'),
    ('employers','area_atuacao','FUNCIONAL',array[]::text[],'SELECTS.employers/EMPLOYER_FIELDS'),
    ('employers','subsetor','FUNCIONAL',array[]::text[],'SELECTS.employers/EMPLOYER_FIELDS'),
    ('employers','cidade','FUNCIONAL',array[]::text[],'SELECTS.employers/EMPLOYER_FIELDS'),
    ('employers','pais','FUNCIONAL',array[]::text[],'SELECTS.employers/EMPLOYER_FIELDS'),
    ('employers','nivel_alemao_minimo','FUNCIONAL',array[]::text[],'SELECTS.employers/EMPLOYER_FIELDS'),
    ('employers','vagas_abertas','FUNCIONAL',array['integer','numeric','text','character varying'],'SELECTS.employers'),
    ('employers','responsavel_interno','FUNCIONAL',array[]::text[],'SELECTS.employers/EMPLOYER_FIELDS'),
    ('employers','contato_principal','FUNCIONAL',array[]::text[],'SELECTS.employers/EMPLOYER_FIELDS'),
    ('employers','email_principal','FUNCIONAL',array[]::text[],'SELECTS.employers/EMPLOYER_FIELDS'),
    ('employers','telefone','FUNCIONAL',array[]::text[],'SELECTS.employers/EMPLOYER_FIELDS'),
    ('employers','site','FUNCIONAL',array[]::text[],'SELECTS.employers/EMPLOYER_FIELDS'),
    ('employers','descricao_resumida','FUNCIONAL',array[]::text[],'SELECTS.employers/EMPLOYER_FIELDS'),
    ('employers','descricao_operacional','FUNCIONAL',array[]::text[],'EMPLOYER_FIELDS'),
    ('employers','prioridade_comercial','FUNCIONAL',array[]::text[],'SELECTS.employers'),
    ('employers','origem_lead','FUNCIONAL',array[]::text[],'SELECTS.employers'),
    ('employers','data_ultimo_contato','FUNCIONAL',array['date','timestamp with time zone','timestamp without time zone','text'],'SELECTS.employers'),
    ('employers','perfis_buscados','FUNCIONAL',array[]::text[],'SELECTS.employers/EMPLOYER_FIELDS'),
    ('employers','requisitos_principais','FUNCIONAL',array[]::text[],'SELECTS.employers/EMPLOYER_FIELDS'),
    ('employers','diferenciais_desejaveis','FUNCIONAL',array[]::text[],'SELECTS.employers/EMPLOYER_FIELDS'),
    ('employers','observacoes_internas','FUNCIONAL',array[]::text[],'SELECTS.employers/EMPLOYER_FIELDS'),
    ('employers','created_at','FUNCIONAL',array['timestamp with time zone','timestamp without time zone'],'SELECTS.employers'),
    ('employers','updated_at','FUNCIONAL',array['timestamp with time zone','timestamp without time zone'],'SELECTS.employers'),
    ('employers','deleted_at','FUNCIONAL',array['timestamp with time zone','timestamp without time zone'],'SELECTS.employers'),
    ('employer_openings','id','OBRIGATORIA',array['uuid','text','character varying'],'SELECTS.openings'),
    ('employer_openings','employer_id','OBRIGATORIA',array['uuid','text','character varying'],'SELECTS.openings'),
    ('employer_openings','title','FUNCIONAL',array[]::text[],'SELECTS.openings'),
    ('employer_openings','quantity','FUNCIONAL',array['integer','numeric','text','character varying'],'SELECTS.openings'),
    ('employer_openings','status','FUNCIONAL',array[]::text[],'SELECTS.openings'),
    ('employer_openings','order_index','FUNCIONAL',array['integer','numeric','text','character varying'],'SELECTS.openings'),
    ('employer_openings','is_active','FUNCIONAL',array['boolean','text','character varying'],'SELECTS.openings'),
    ('employer_openings','deleted_at','FUNCIONAL',array['timestamp with time zone','timestamp without time zone'],'SELECTS.openings'),
    ('employer_openings','location','FUNCIONAL',array[]::text[],'SELECTS.openings'),
    ('employer_openings','area','FUNCIONAL',array[]::text[],'SELECTS.openings'),
    ('employer_openings','external_url','FUNCIONAL',array[]::text[],'SELECTS.openings'),
    ('employer_openings','language_requirement','FUNCIONAL',array[]::text[],'SELECTS.openings'),
    ('employer_openings','recognition_requirement','FUNCIONAL',array[]::text[],'SELECTS.openings'),
    ('employer_openings','verified_at','FUNCIONAL',array['date','timestamp with time zone','timestamp without time zone','text'],'SELECTS.openings'),
    ('employer_openings','description','FUNCIONAL',array[]::text[],'SELECTS.openings'),
    ('employer_openings','source','FUNCIONAL',array[]::text[],'SELECTS.openings'),
    ('employer_openings','created_at','FUNCIONAL',array['timestamp with time zone','timestamp without time zone'],'SELECTS.openings'),
    ('employer_openings','updated_at','FUNCIONAL',array['timestamp with time zone','timestamp without time zone'],'SELECTS.openings'),

    -- Seleções modernas e formatos legados ainda lidos pelo CRM.
    ('talent_opportunity_matches','id','OBRIGATORIA',array['uuid','text','character varying'],'SELECTS.matches'),
    ('talent_opportunity_matches','talent_id','OBRIGATORIA',array['text','character varying','uuid'],'SELECTS.matches'),
    ('talent_opportunity_matches','opening_id','FUNCIONAL',array['uuid','text','character varying'],'SELECTS.matches'),
    ('talent_opportunity_matches','employer_id','FUNCIONAL',array['uuid','text','character varying'],'SELECTS.matches'),
    ('talent_opportunity_matches','stage','FUNCIONAL',array[]::text[],'SELECTS.matches'),
    ('talent_opportunity_matches','status','FUNCIONAL',array[]::text[],'SELECTS.matches'),
    ('talent_opportunity_matches','priority','FUNCIONAL',array[]::text[],'SELECTS.matches'),
    ('talent_opportunity_matches','overall_score','FUNCIONAL',array['numeric','integer','text','character varying'],'SELECTS.matches'),
    ('talent_opportunity_matches','professional_score','FUNCIONAL',array['numeric','integer','text','character varying'],'SELECTS.matches'),
    ('talent_opportunity_matches','language_score','FUNCIONAL',array['numeric','integer','text','character varying'],'SELECTS.matches'),
    ('talent_opportunity_matches','mobility_score','FUNCIONAL',array['numeric','integer','text','character varying'],'SELECTS.matches'),
    ('talent_opportunity_matches','document_score','FUNCIONAL',array['numeric','integer','text','character varying'],'SELECTS.matches'),
    ('talent_opportunity_matches','viability','FUNCIONAL',array[]::text[],'SELECTS.matches'),
    ('talent_opportunity_matches','reasons','FUNCIONAL',array[]::text[],'SELECTS.matches'),
    ('talent_opportunity_matches','barriers','FUNCIONAL',array[]::text[],'SELECTS.matches'),
    ('talent_opportunity_matches','next_action','FUNCIONAL',array[]::text[],'SELECTS.matches'),
    ('talent_opportunity_matches','next_action_at','FUNCIONAL',array['date','timestamp with time zone','timestamp without time zone','text'],'SELECTS.matches'),
    ('talent_opportunity_matches','owner_username','FUNCIONAL',array[]::text[],'SELECTS.matches'),
    ('talent_opportunity_matches','sent_at','FUNCIONAL',array['date','timestamp with time zone','timestamp without time zone','text'],'SELECTS.matches'),
    ('talent_opportunity_matches','responded_at','FUNCIONAL',array['date','timestamp with time zone','timestamp without time zone','text'],'SELECTS.matches'),
    ('talent_opportunity_matches','created_at','FUNCIONAL',array['timestamp with time zone','timestamp without time zone'],'SELECTS.matches'),
    ('talent_opportunity_matches','updated_at','FUNCIONAL',array['timestamp with time zone','timestamp without time zone'],'SELECTS.matches'),
    ('candidate_employer_matches','id','OBRIGATORIA',array['uuid','text','character varying'],'SELECTS.legacyMatches'),
    ('candidate_employer_matches','candidato_id','FUNCIONAL',array['text','character varying','uuid'],'SELECTS.legacyMatches'),
    ('candidate_employer_matches','empregador_id','FUNCIONAL',array['uuid','text','character varying'],'SELECTS.legacyMatches'),
    ('candidate_employer_matches','status_vinculo','LEGADO',array[]::text[],'SELECTS.legacyMatches'),
    ('candidate_employer_matches','prioridade','LEGADO',array[]::text[],'SELECTS.legacyMatches'),
    ('candidate_employer_matches','match_strength','LEGADO',array[]::text[],'SELECTS.legacyMatches'),
    ('candidate_employer_matches','is_primary','LEGADO',array['boolean','text','character varying'],'SELECTS.legacyMatches'),
    ('candidate_employer_matches','data_envio','LEGADO',array['date','timestamp with time zone','timestamp without time zone','text'],'SELECTS.legacyMatches'),
    ('candidate_employer_matches','data_retorno','LEGADO',array['date','timestamp with time zone','timestamp without time zone','text'],'SELECTS.legacyMatches'),
    ('candidate_employer_matches','elegivel','LEGADO',array['boolean','text','character varying'],'SELECTS.legacyMatches'),
    ('candidate_employer_matches','motivo_encaixe','LEGADO',array[]::text[],'SELECTS.legacyMatches'),
    ('candidate_employer_matches','riscos_ressalvas','LEGADO',array[]::text[],'SELECTS.legacyMatches'),
    ('candidate_employer_matches','proxima_acao','LEGADO',array[]::text[],'SELECTS.legacyMatches'),
    ('candidate_employer_matches','observacoes','LEGADO',array[]::text[],'SELECTS.legacyMatches'),
    ('candidate_employer_matches','created_at','LEGADO',array['timestamp with time zone','timestamp without time zone'],'SELECTS.legacyMatches'),
    ('candidate_employer_matches','updated_at','LEGADO',array['timestamp with time zone','timestamp without time zone'],'SELECTS.legacyMatches'),
    ('candidate_employer_links','id','OBRIGATORIA',array['uuid','text','character varying'],'compatibilidade legada'),
    ('candidate_employer_links','candidate_id','LEGADO',array['text','character varying','uuid'],'compatibilidade legada'),
    ('candidate_employer_links','employer_id','LEGADO',array['uuid','text','character varying'],'compatibilidade legada'),
    ('candidate_employer_links','status_vinculo','LEGADO',array[]::text[],'compatibilidade legada'),
    ('candidate_employer_links','proximo_followup_em','LEGADO',array['date','timestamp with time zone','timestamp without time zone','text'],'compatibilidade legada'),
    ('candidate_employer_links','responsavel_interno','LEGADO',array[]::text[],'compatibilidade legada'),
    ('candidate_employer_links','motivo_match','LEGADO',array[]::text[],'compatibilidade legada'),
    ('candidate_employer_links','observacao_rh','LEGADO',array[]::text[],'compatibilidade legada'),
    ('candidate_employer_links','proxima_acao','LEGADO',array[]::text[],'compatibilidade legada'),

    -- Tabelas do mapeamento previstas na aplicação aditiva V2.2.
    ('talent_mapping_profiles','id','OBRIGATORIA',array['text','character varying','uuid'],'10_additive.sql'),
    ('talent_mapping_profiles','lista_nectanet','FUNCIONAL',array[]::text[],'10_additive.sql'),
    ('talent_mapping_profiles','visto','FUNCIONAL',array[]::text[],'10_additive.sql'),
    ('talent_mapping_profiles','profissional_qualificado','FUNCIONAL',array[]::text[],'10_additive.sql'),
    ('talent_mapping_profiles','novo_cv','FUNCIONAL',array[]::text[],'10_additive.sql'),
    ('talent_mapping_profiles','cluster','FUNCIONAL',array[]::text[],'10_additive.sql'),
    ('talent_mapping_profiles','ingles','FUNCIONAL',array[]::text[],'10_additive.sql'),
    ('talent_mapping_profiles','outros_idiomas','FUNCIONAL',array[]::text[],'10_additive.sql'),
    ('talent_mapping_profiles','employer_primary_id','FUNCIONAL',array['uuid','text','character varying'],'10_additive.sql'),
    ('talent_mapping_profiles','employer_alt1_id','FUNCIONAL',array['uuid','text','character varying'],'10_additive.sql'),
    ('talent_mapping_profiles','employer_alt2_id','FUNCIONAL',array['uuid','text','character varying'],'10_additive.sql'),
    ('talent_mapping_profiles','observacao_apresentacao','FUNCIONAL',array[]::text[],'10_additive.sql'),
    ('talent_mapping_profiles','perfil_titulo','FUNCIONAL',array[]::text[],'10_additive.sql'),
    ('talent_mapping_profiles','perfil_comprovado','FUNCIONAL',array[]::text[],'10_additive.sql'),
    ('talent_mapping_profiles','idiomas_contexto','FUNCIONAL',array[]::text[],'10_additive.sql'),
    ('talent_mapping_profiles','regra_revisao','FUNCIONAL',array[]::text[],'10_additive.sql'),
    ('talent_mapping_profiles','premissa_projecao','FUNCIONAL',array[]::text[],'10_additive.sql'),
    ('talent_mapping_profiles','barreira_principal','FUNCIONAL',array[]::text[],'10_additive.sql'),
    ('talent_mapping_profiles','prioridade_mapeamento','FUNCIONAL',array[]::text[],'10_additive.sql'),
    ('talent_mapping_profiles','best_nectanet_item_id','FUNCIONAL',array['uuid','text','character varying'],'10_additive.sql'),
    ('talent_mapping_profiles','best_external_item_id','FUNCIONAL',array['uuid','text','character varying'],'10_additive.sql'),
    ('talent_mapping_profiles','created_at','FUNCIONAL',array['timestamp with time zone','timestamp without time zone'],'10_additive.sql'),
    ('talent_mapping_profiles','updated_at','FUNCIONAL',array['timestamp with time zone','timestamp without time zone'],'10_additive.sql'),
    ('talent_mapping_items','id','OBRIGATORIA',array['uuid','text','character varying'],'10_additive.sql'),
    ('talent_mapping_items','talent_id','OBRIGATORIA',array['text','character varying','uuid'],'10_additive.sql'),
    ('talent_mapping_items','employer_id','FUNCIONAL',array['uuid','text','character varying'],'10_additive.sql'),
    ('talent_mapping_items','employer_name','FUNCIONAL',array[]::text[],'10_additive.sql'),
    ('talent_mapping_items','opening_id','FUNCIONAL',array['uuid','text','character varying'],'10_additive.sql'),
    ('talent_mapping_items','source_table','FUNCIONAL',array[]::text[],'10_additive.sql'),
    ('talent_mapping_items','source_record_id','FUNCIONAL',array[]::text[],'10_additive.sql'),
    ('talent_mapping_items','nectanet','FUNCIONAL',array[]::text[],'10_additive.sql'),
    ('talent_mapping_items','vacancy_status','FUNCIONAL',array[]::text[],'10_additive.sql'),
    ('talent_mapping_items','professional_score','FUNCIONAL',array['numeric','integer','text','character varying'],'10_additive.sql'),
    ('talent_mapping_items','current_viability_score','FUNCIONAL',array['numeric','integer','text','character varying'],'10_additive.sql'),
    ('talent_mapping_items','projected_b1_score','FUNCIONAL',array['numeric','integer','text','character varying'],'10_additive.sql'),
    ('talent_mapping_items','vacancy_situation','FUNCIONAL',array[]::text[],'10_additive.sql'),
    ('talent_mapping_items','type_area','FUNCIONAL',array[]::text[],'10_additive.sql'),
    ('talent_mapping_items','fit_reasons','FUNCIONAL',array[]::text[],'10_additive.sql'),
    ('talent_mapping_items','barriers','FUNCIONAL',array[]::text[],'10_additive.sql'),
    ('talent_mapping_items','language_requirement','FUNCIONAL',array[]::text[],'10_additive.sql'),
    ('talent_mapping_items','recognition_requirement','FUNCIONAL',array[]::text[],'10_additive.sql'),
    ('talent_mapping_items','location','FUNCIONAL',array[]::text[],'10_additive.sql'),
    ('talent_mapping_items','contact','FUNCIONAL',array[]::text[],'10_additive.sql'),
    ('talent_mapping_items','official_url','FUNCIONAL',array[]::text[],'10_additive.sql'),
    ('talent_mapping_items','verified_on','FUNCIONAL',array['date','timestamp with time zone','timestamp without time zone','text'],'10_additive.sql'),
    ('talent_mapping_items','verification_notes','FUNCIONAL',array[]::text[],'10_additive.sql'),
    ('talent_mapping_items','archived_at','FUNCIONAL',array['timestamp with time zone','timestamp without time zone'],'10_additive.sql'),
    ('talent_mapping_items','created_at','FUNCIONAL',array['timestamp with time zone','timestamp without time zone'],'10_additive.sql'),
    ('talent_mapping_items','updated_at','FUNCIONAL',array['timestamp with time zone','timestamp without time zone'],'10_additive.sql'),
    ('talent_mapping_partners','id','OBRIGATORIA',array['uuid','text','character varying'],'10_additive.sql'),
    ('talent_mapping_partners','is_nectanet','FUNCIONAL',array[]::text[],'10_additive.sql'),
    ('talent_mapping_partners','source','FUNCIONAL',array[]::text[],'10_additive.sql'),
    ('talent_mapping_partners','ceo_name','FUNCIONAL',array[]::text[],'10_additive.sql'),
    ('talent_mapping_partners','ceo_email','FUNCIONAL',array[]::text[],'10_additive.sql'),
    ('talent_mapping_partners','hr_name','FUNCIONAL',array[]::text[],'10_additive.sql'),
    ('talent_mapping_partners','hr_email','FUNCIONAL',array[]::text[],'10_additive.sql'),
    ('talent_mapping_partners','contact_status','FUNCIONAL',array[]::text[],'10_additive.sql'),
    ('talent_mapping_partners','notes','FUNCIONAL',array[]::text[],'10_additive.sql'),
    ('talent_mapping_partners','send_email','FUNCIONAL',array[]::text[],'10_additive.sql'),
    ('talent_mapping_partners','sector','FUNCIONAL',array[]::text[],'10_additive.sql'),
    ('talent_mapping_partners','description','FUNCIONAL',array[]::text[],'10_additive.sql'),
    ('talent_mapping_partners','openings_note','FUNCIONAL',array[]::text[],'10_additive.sql'),
    ('talent_mapping_partners','created_at','FUNCIONAL',array['timestamp with time zone','timestamp without time zone'],'10_additive.sql'),
    ('talent_mapping_partners','updated_at','FUNCIONAL',array['timestamp with time zone','timestamp without time zone'],'10_additive.sql'),

    -- Planejamento, acervo e agenda.
    ('organizational_plan_entries','id','OBRIGATORIA',array['uuid','text','character varying'],'organization-v2.js'),
    ('organizational_plan_entries','employer_id','FUNCIONAL',array['uuid','text','character varying'],'organization-v2.js'),
    ('organizational_plan_entries','month_ref','FUNCIONAL',array[]::text[],'organization-v2.js'),
    ('organizational_plan_entries','activity_label','FUNCIONAL',array[]::text[],'organization-v2.js'),
    ('organizational_plan_entries','responsavel','FUNCIONAL',array[]::text[],'organization-v2.js'),
    ('organizational_plan_entries','status','FUNCIONAL',array[]::text[],'organization-v2.js'),
    ('organizational_plan_entries','start_date','FUNCIONAL',array['date','timestamp with time zone','timestamp without time zone','text'],'organization-v2.js'),
    ('organizational_plan_entries','end_date','FUNCIONAL',array['date','timestamp with time zone','timestamp without time zone','text'],'organization-v2.js'),
    ('organizational_plan_entries','obs','FUNCIONAL',array[]::text[],'organization-v2.js'),
    ('organizational_plan_entries','activity_type','FUNCIONAL',array[]::text[],'organization-v2.js'),
    ('organizational_plan_entries','activity_key','FUNCIONAL',array[]::text[],'organization-v2.js'),
    ('organizational_plan_entries','order_index','FUNCIONAL',array['integer','numeric','text','character varying'],'organization-v2.js'),
    ('organizational_plan_entries','deleted_at','FUNCIONAL',array['timestamp with time zone','timestamp without time zone'],'organization-v2.js'),
    ('organizational_plan_entries','employer_name_snapshot','FUNCIONAL',array[]::text[],'organization-v2.js'),
    ('organizational_plan_entries','created_at','FUNCIONAL',array['timestamp with time zone','timestamp without time zone'],'organization-v2.js'),
    ('organizational_plan_entries','updated_at','FUNCIONAL',array['timestamp with time zone','timestamp without time zone'],'organization-v2.js'),
    ('organizational_meetings','id','OBRIGATORIA',array['uuid','text','character varying'],'organization-v2.js'),
    ('organizational_meetings','title','FUNCIONAL',array[]::text[],'organization-v2.js'),
    ('organizational_meetings','employer_id','FUNCIONAL',array['uuid','text','character varying'],'organization-v2.js'),
    ('organizational_meetings','scheduled_at','FUNCIONAL',array['date','timestamp with time zone','timestamp without time zone','text'],'organization-v2.js'),
    ('organizational_meetings','month_ref','FUNCIONAL',array[]::text[],'organization-v2.js'),
    ('organizational_meetings','week_label','FUNCIONAL',array[]::text[],'organization-v2.js'),
    ('organizational_meetings','owner_name','FUNCIONAL',array[]::text[],'organization-v2.js'),
    ('organizational_meetings','status','FUNCIONAL',array[]::text[],'organization-v2.js'),
    ('organizational_meetings','topic','FUNCIONAL',array[]::text[],'organization-v2.js'),
    ('organizational_meetings','decision_summary','FUNCIONAL',array[]::text[],'organization-v2.js'),
    ('organizational_meetings','resolved_items','FUNCIONAL',array[]::text[],'organization-v2.js'),
    ('organizational_meetings','pending_items','FUNCIONAL',array[]::text[],'organization-v2.js'),
    ('organizational_meetings','next_action','FUNCIONAL',array[]::text[],'organization-v2.js'),
    ('organizational_meetings','notes','FUNCIONAL',array[]::text[],'organization-v2.js'),
    ('organizational_meetings','meeting_scope','FUNCIONAL',array[]::text[],'organization-v2.js'),
    ('organizational_meetings','group_name','FUNCIONAL',array[]::text[],'organization-v2.js'),
    ('organizational_meetings','deleted_at','FUNCIONAL',array['timestamp with time zone','timestamp without time zone'],'organization-v2.js'),
    ('organizational_meetings','employer_name_snapshot','FUNCIONAL',array[]::text[],'organization-v2.js'),
    ('organizational_meetings','created_at','FUNCIONAL',array['timestamp with time zone','timestamp without time zone'],'organization-v2.js'),
    ('organizational_meetings','updated_at','FUNCIONAL',array['timestamp with time zone','timestamp without time zone'],'organization-v2.js'),
    ('operational_tasks','id','OBRIGATORIA',array['uuid','text','character varying'],'organization-v2.js'),
    ('operational_tasks','title','FUNCIONAL',array[]::text[],'organization-v2.js'),
    ('operational_tasks','description','FUNCIONAL',array[]::text[],'organization-v2.js'),
    ('operational_tasks','employer_id','FUNCIONAL',array['uuid','text','character varying'],'organization-v2.js'),
    ('operational_tasks','month_ref','FUNCIONAL',array[]::text[],'organization-v2.js'),
    ('operational_tasks','owner_user_key','FUNCIONAL',array[]::text[],'organization-v2.js'),
    ('operational_tasks','team_scope','FUNCIONAL',array[]::text[],'organization-v2.js'),
    ('operational_tasks','priority','FUNCIONAL',array[]::text[],'organization-v2.js'),
    ('operational_tasks','status','FUNCIONAL',array[]::text[],'organization-v2.js'),
    ('operational_tasks','start_date','FUNCIONAL',array['date','timestamp with time zone','timestamp without time zone','text'],'organization-v2.js'),
    ('operational_tasks','due_date','FUNCIONAL',array['date','timestamp with time zone','timestamp without time zone','text'],'organization-v2.js'),
    ('operational_tasks','notes','FUNCIONAL',array[]::text[],'organization-v2.js'),
    ('operational_tasks','context_type','FUNCIONAL',array[]::text[],'organization-v2.js'),
    ('operational_tasks','assigned_user_key','FUNCIONAL',array[]::text[],'organization-v2.js'),
    ('operational_tasks','completed_at','FUNCIONAL',array['timestamp with time zone','timestamp without time zone','date','text'],'organization-v2.js'),
    ('operational_tasks','sort_index','FUNCIONAL',array['integer','numeric','text','character varying'],'organization-v2.js'),
    ('operational_tasks','is_recurring','FUNCIONAL',array['boolean','text','character varying'],'organization-v2.js'),
    ('operational_tasks','deleted_at','FUNCIONAL',array['timestamp with time zone','timestamp without time zone'],'organization-v2.js'),
    ('operational_tasks','meeting_id','FUNCIONAL',array['uuid','text','character varying'],'organization-v2.js'),
    ('operational_tasks','created_at','FUNCIONAL',array['timestamp with time zone','timestamp without time zone'],'organization-v2.js'),
    ('operational_tasks','updated_at','FUNCIONAL',array['timestamp with time zone','timestamp without time zone'],'organization-v2.js'),
    ('operational_metrics','id','OBRIGATORIA',array['uuid','text','character varying'],'organization-v2.js'),
    ('operational_metrics','metric_label','FUNCIONAL',array[]::text[],'organization-v2.js'),
    ('operational_metrics','month_ref','FUNCIONAL',array[]::text[],'organization-v2.js'),
    ('operational_metrics','owner_user_key','FUNCIONAL',array[]::text[],'organization-v2.js'),
    ('operational_metrics','target_value','FUNCIONAL',array['numeric','integer','text','character varying'],'organization-v2.js'),
    ('operational_metrics','actual_value','FUNCIONAL',array['numeric','integer','text','character varying'],'organization-v2.js'),
    ('operational_metrics','team_scope','FUNCIONAL',array[]::text[],'organization-v2.js'),
    ('operational_metrics','notes','FUNCIONAL',array[]::text[],'organization-v2.js'),
    ('operational_metrics','metric_key','FUNCIONAL',array[]::text[],'organization-v2.js'),
    ('operational_metrics','deleted_at','FUNCIONAL',array['timestamp with time zone','timestamp without time zone'],'organization-v2.js'),
    ('operational_metrics','created_at','FUNCIONAL',array['timestamp with time zone','timestamp without time zone'],'organization-v2.js'),
    ('operational_metrics','updated_at','FUNCIONAL',array['timestamp with time zone','timestamp without time zone'],'organization-v2.js'),
    ('organizational_weekly_summaries','id','OBRIGATORIA',array['uuid','text','character varying'],'organization-v2.js'),
    ('organizational_weekly_summaries','employer_id','FUNCIONAL',array['uuid','text','character varying'],'organization-v2.js'),
    ('organizational_weekly_summaries','month_ref','FUNCIONAL',array[]::text[],'organization-v2.js'),
    ('organizational_weekly_summaries','week_label','FUNCIONAL',array[]::text[],'organization-v2.js'),
    ('organizational_weekly_summaries','owner_name','FUNCIONAL',array[]::text[],'organization-v2.js'),
    ('organizational_weekly_summaries','period_start','FUNCIONAL',array['date','timestamp with time zone','timestamp without time zone','text'],'organization-v2.js'),
    ('organizational_weekly_summaries','period_end','FUNCIONAL',array['date','timestamp with time zone','timestamp without time zone','text'],'organization-v2.js'),
    ('organizational_weekly_summaries','status','FUNCIONAL',array[]::text[],'organization-v2.js'),
    ('organizational_weekly_summaries','what_was_done','FUNCIONAL',array[]::text[],'organization-v2.js'),
    ('organizational_weekly_summaries','result_summary','FUNCIONAL',array[]::text[],'organization-v2.js'),
    ('organizational_weekly_summaries','next_action','FUNCIONAL',array[]::text[],'organization-v2.js'),
    ('organizational_weekly_summaries','notes','FUNCIONAL',array[]::text[],'organization-v2.js'),
    ('organizational_weekly_summaries','summary_scope','FUNCIONAL',array[]::text[],'organization-v2.js'),
    ('organizational_weekly_summaries','order_index','FUNCIONAL',array['integer','numeric','text','character varying'],'organization-v2.js'),
    ('organizational_weekly_summaries','deleted_at','FUNCIONAL',array['timestamp with time zone','timestamp without time zone'],'organization-v2.js'),
    ('organizational_weekly_summaries','employer_name_snapshot','FUNCIONAL',array[]::text[],'organization-v2.js'),
    ('organizational_weekly_summaries','created_at','FUNCIONAL',array['timestamp with time zone','timestamp without time zone'],'organization-v2.js'),
    ('organizational_weekly_summaries','updated_at','FUNCIONAL',array['timestamp with time zone','timestamp without time zone'],'organization-v2.js'),
    ('organizational_replacement_requests','id','OBRIGATORIA',array['uuid','text','character varying'],'organization-v2.js'),
    ('organizational_replacement_requests','employer_id','FUNCIONAL',array['uuid','text','character varying'],'organization-v2.js'),
    ('organizational_replacement_requests','profile_needed','FUNCIONAL',array[]::text[],'organization-v2.js'),
    ('organizational_replacement_requests','replaces_candidate_name_snapshot','FUNCIONAL',array[]::text[],'organization-v2.js'),
    ('organizational_replacement_requests','priority','FUNCIONAL',array[]::text[],'organization-v2.js'),
    ('organizational_replacement_requests','search_status','FUNCIONAL',array[]::text[],'organization-v2.js'),
    ('organizational_replacement_requests','notes','FUNCIONAL',array[]::text[],'organization-v2.js'),
    ('organizational_replacement_requests','deleted_at','FUNCIONAL',array['timestamp with time zone','timestamp without time zone'],'organization-v2.js'),
    ('organizational_replacement_requests','employer_name_snapshot','FUNCIONAL',array[]::text[],'organization-v2.js'),
    ('organizational_replacement_requests','created_at','FUNCIONAL',array['timestamp with time zone','timestamp without time zone'],'organization-v2.js'),
    ('organizational_replacement_requests','updated_at','FUNCIONAL',array['timestamp with time zone','timestamp without time zone'],'organization-v2.js'),
    ('org_ui_state_snapshots','id','OBRIGATORIA',array['uuid','text','character varying'],'organization-v2.js'),
    ('org_ui_state_snapshots','app_key','FUNCIONAL',array[]::text[],'organization-v2.js'),
    ('org_ui_state_snapshots','payload','FUNCIONAL',array['jsonb','json','text'],'organization-v2.js'),
    ('org_ui_state_snapshots','updated_at','FUNCIONAL',array['timestamp with time zone','timestamp without time zone'],'organization-v2.js'),
    ('org_ui_state_snapshots','created_at','FUNCIONAL',array['timestamp with time zone','timestamp without time zone'],'organization-v2.js'),
    ('crm_activities','id','OBRIGATORIA',array['uuid','text','character varying'],'SELECTS.activities'),
    ('crm_activities','title','FUNCIONAL',array[]::text[],'SELECTS.activities'),
    ('crm_activities','activity_type','FUNCIONAL',array[]::text[],'SELECTS.activities'),
    ('crm_activities','status','FUNCIONAL',array[]::text[],'SELECTS.activities'),
    ('crm_activities','priority','FUNCIONAL',array[]::text[],'SELECTS.activities'),
    ('crm_activities','due_at','FUNCIONAL',array['date','timestamp with time zone','timestamp without time zone','text'],'SELECTS.activities'),
    ('crm_activities','completed_at','FUNCIONAL',array['date','timestamp with time zone','timestamp without time zone','text'],'SELECTS.activities'),
    ('crm_activities','owner_username','FUNCIONAL',array[]::text[],'SELECTS.activities'),
    ('crm_activities','talent_id','FUNCIONAL',array['text','character varying','uuid'],'SELECTS.activities'),
    ('crm_activities','employer_id','FUNCIONAL',array['uuid','text','character varying'],'SELECTS.activities'),
    ('crm_activities','opening_id','FUNCIONAL',array['uuid','text','character varying'],'SELECTS.activities'),
    ('crm_activities','contact_id','FUNCIONAL',array['uuid','text','character varying'],'SELECTS.activities'),
    ('crm_activities','enrollment_id','FUNCIONAL',array['uuid','text','character varying'],'SELECTS.activities'),
    ('crm_activities','notes','FUNCIONAL',array[]::text[],'SELECTS.activities'),
    ('crm_activities','outcome','FUNCIONAL',array[]::text[],'SELECTS.activities'),
    ('crm_activities','created_by','FUNCIONAL',array['uuid','text','character varying'],'SELECTS.activities'),
    ('crm_activities','created_at','FUNCIONAL',array['timestamp with time zone','timestamp without time zone'],'SELECTS.activities'),
    ('crm_activities','updated_at','FUNCIONAL',array['timestamp with time zone','timestamp without time zone'],'SELECTS.activities'),

    -- Contatos.
    ('contact_records','id','OBRIGATORIA',array['uuid','text','character varying'],'contacts-v2.js/fixture'),
    ('contact_records','display_name','FUNCIONAL',array[]::text[],'contacts-v2.js/fixture'),
    ('contact_records','entity_type','FUNCIONAL',array[]::text[],'contacts-v2.js/fixture'),
    ('contact_records','email','FUNCIONAL',array[]::text[],'contacts-v2.js/fixture'),
    ('contact_records','phone','FUNCIONAL',array[]::text[],'contacts-v2.js/fixture'),
    ('contact_records','whatsapp','FUNCIONAL',array[]::text[],'contacts-v2.js/fixture'),
    ('contact_records','secondary_email','FUNCIONAL',array[]::text[],'contacts-v2.js/fixture'),
    ('contact_records','city','FUNCIONAL',array[]::text[],'contacts-v2.js/fixture'),
    ('contact_records','country','FUNCIONAL',array[]::text[],'contacts-v2.js/fixture'),
    ('contact_records','status','FUNCIONAL',array[]::text[],'contacts-v2.js/fixture'),
    ('contact_records','relationship_stage','FUNCIONAL',array[]::text[],'contacts-v2.js/fixture'),
    ('contact_records','priority','FUNCIONAL',array[]::text[],'contacts-v2.js/fixture'),
    ('contact_records','owner_username','FUNCIONAL',array[]::text[],'contacts-v2.js/fixture'),
    ('contact_records','job_title','FUNCIONAL',array[]::text[],'contacts-v2.js/fixture'),
    ('contact_records','legal_name','FUNCIONAL',array[]::text[],'contacts-v2.js/fixture'),
    ('contact_records','notes','FUNCIONAL',array[]::text[],'contacts-v2.js/fixture'),
    ('contact_records','source_system','FUNCIONAL',array[]::text[],'contacts-v2.js/fixture'),
    ('contact_records','source_record_id','FUNCIONAL',array[]::text[],'contacts-v2.js/fixture'),
    ('contact_records','archived_at','FUNCIONAL',array['timestamp with time zone','timestamp without time zone'],'contacts-v2.js/fixture'),
    ('contact_records','primary_organization_id','FUNCIONAL',array['uuid','text','character varying'],'contacts-v2.js/fixture'),
    ('contact_records','website','FUNCIONAL',array[]::text[],'contacts-v2.js/fixture'),
    ('contact_records','linkedin_url','FUNCIONAL',array[]::text[],'contacts-v2.js/fixture'),
    ('contact_records','language','FUNCIONAL',array[]::text[],'contacts-v2.js/fixture'),
    ('contact_records','preferred_channel','FUNCIONAL',array[]::text[],'contacts-v2.js/fixture'),
    ('contact_records','address_line','FUNCIONAL',array[]::text[],'contacts-v2.js/fixture'),
    ('contact_records','postal_code','FUNCIONAL',array[]::text[],'contacts-v2.js/fixture'),
    ('contact_records','retention_review_at','FUNCIONAL',array['date','timestamp with time zone','timestamp without time zone','text'],'contacts-v2.js/fixture'),
    ('contact_records','created_at','FUNCIONAL',array['timestamp with time zone','timestamp without time zone'],'contacts-v2.js/fixture'),
    ('contact_records','updated_at','FUNCIONAL',array['timestamp with time zone','timestamp without time zone'],'contacts-v2.js/fixture'),
    ('contact_categories','id','OBRIGATORIA',array['uuid','text','character varying'],'contacts-v2.js'),
    ('contact_categories','name','FUNCIONAL',array[]::text[],'contacts-v2.js'),
    ('contact_categories','slug','FUNCIONAL',array[]::text[],'contacts-v2.js'),
    ('contact_categories','is_system','FUNCIONAL',array['boolean','text','character varying'],'contacts-v2.js'),
    ('contact_categories','is_active','FUNCIONAL',array['boolean','text','character varying'],'contacts-v2.js'),
    ('contact_categories','color','FUNCIONAL',array[]::text[],'contacts-v2.js'),
    ('contact_categories','sort_order','FUNCIONAL',array['integer','numeric','text','character varying'],'contacts-v2.js'),
    ('contact_categories','created_at','FUNCIONAL',array['timestamp with time zone','timestamp without time zone'],'contacts-v2.js'),
    ('contact_categories','updated_at','FUNCIONAL',array['timestamp with time zone','timestamp without time zone'],'contacts-v2.js'),
    ('contact_record_categories','contact_id','OBRIGATORIA',array['uuid','text','character varying'],'contacts-v2.js'),
    ('contact_record_categories','category_id','OBRIGATORIA',array['uuid','text','character varying'],'contacts-v2.js'),
    ('contact_record_categories','created_at','FUNCIONAL',array['timestamp with time zone','timestamp without time zone'],'contacts-v2.js'),
    ('contact_relationships','id','OBRIGATORIA',array['uuid','text','character varying'],'contacts-v2.js'),
    ('contact_relationships','contact_id','OBRIGATORIA',array['uuid','text','character varying'],'contacts-v2.js'),
    ('contact_relationships','related_contact_id','FUNCIONAL',array['uuid','text','character varying'],'contacts-v2.js'),
    ('contact_relationships','relationship_label','FUNCIONAL',array[]::text[],'contacts-v2.js'),
    ('contact_relationships','is_primary','FUNCIONAL',array['boolean','text','character varying'],'contacts-v2.js'),
    ('contact_relationships','notes','FUNCIONAL',array[]::text[],'contacts-v2.js'),
    ('contact_interactions','id','OBRIGATORIA',array['uuid','text','character varying'],'contacts-v2.js'),
    ('contact_interactions','contact_id','OBRIGATORIA',array['uuid','text','character varying'],'contacts-v2.js'),
    ('contact_interactions','occurred_at','FUNCIONAL',array['date','timestamp with time zone','timestamp without time zone','text'],'contacts-v2.js'),
    ('contact_interactions','interaction_type','FUNCIONAL',array[]::text[],'contacts-v2.js'),
    ('contact_interactions','subject','FUNCIONAL',array[]::text[],'contacts-v2.js'),
    ('contact_interactions','summary','FUNCIONAL',array[]::text[],'contacts-v2.js'),
    ('contact_interactions','outcome','FUNCIONAL',array[]::text[],'contacts-v2.js'),
    ('contact_followups','id','OBRIGATORIA',array['uuid','text','character varying'],'contacts-v2.js/records'),
    ('contact_followups','title','FUNCIONAL',array[]::text[],'contacts-v2.js/records'),
    ('contact_followups','due_at','FUNCIONAL',array['date','timestamp with time zone','timestamp without time zone','text'],'contacts-v2.js/records'),
    ('contact_followups','assigned_username','FUNCIONAL',array[]::text[],'contacts-v2.js/records'),
    ('contact_followups','status','FUNCIONAL',array[]::text[],'contacts-v2.js/records'),
    ('contact_followups','priority','FUNCIONAL',array[]::text[],'contacts-v2.js/records'),
    ('contact_followups','notes','FUNCIONAL',array[]::text[],'contacts-v2.js/records'),
    ('contact_followups','contact_id','FUNCIONAL',array['uuid','text','character varying'],'contacts-v2.js/records'),
    ('contact_followups','completed_at','FUNCIONAL',array['date','timestamp with time zone','timestamp without time zone','text'],'contacts-v2.js/records'),
    ('contact_followups','created_at','FUNCIONAL',array['timestamp with time zone','timestamp without time zone'],'contacts-v2.js/records'),
    ('contact_followups','updated_at','FUNCIONAL',array['timestamp with time zone','timestamp without time zone'],'contacts-v2.js/records'),

    -- Alemão.
    ('german_course_classes','id','OBRIGATORIA',array['uuid','text','character varying'],'german-v2.js'),
    ('german_course_classes','code','FUNCIONAL',array[]::text[],'german-v2.js'),
    ('german_course_classes','name','FUNCIONAL',array[]::text[],'german-v2.js'),
    ('german_course_classes','provider','FUNCIONAL',array[]::text[],'german-v2.js'),
    ('german_course_classes','teacher_name','FUNCIONAL',array[]::text[],'german-v2.js'),
    ('german_course_classes','teacher_contact_id','FUNCIONAL',array['uuid','text','character varying'],'german-v2.js'),
    ('german_course_classes','level_start','FUNCIONAL',array[]::text[],'german-v2.js'),
    ('german_course_classes','level_target','FUNCIONAL',array[]::text[],'german-v2.js'),
    ('german_course_classes','start_date','FUNCIONAL',array['date','timestamp with time zone','timestamp without time zone','text'],'german-v2.js'),
    ('german_course_classes','expected_end_date','FUNCIONAL',array['date','timestamp with time zone','timestamp without time zone','text'],'german-v2.js'),
    ('german_course_classes','schedule_text','FUNCIONAL',array[]::text[],'german-v2.js'),
    ('german_course_classes','modality','FUNCIONAL',array[]::text[],'german-v2.js'),
    ('german_course_classes','capacity','FUNCIONAL',array['integer','numeric','text','character varying'],'german-v2.js'),
    ('german_course_classes','status','FUNCIONAL',array[]::text[],'german-v2.js'),
    ('german_course_classes','meeting_link','FUNCIONAL',array[]::text[],'german-v2.js'),
    ('german_course_classes','drive_link','FUNCIONAL',array[]::text[],'german-v2.js'),
    ('german_course_classes','notes','FUNCIONAL',array[]::text[],'german-v2.js'),
    ('german_course_classes','created_at','FUNCIONAL',array['timestamp with time zone','timestamp without time zone'],'german-v2.js'),
    ('german_course_classes','updated_at','FUNCIONAL',array['timestamp with time zone','timestamp without time zone'],'german-v2.js'),
    ('german_course_enrollments','id','OBRIGATORIA',array['uuid','text','character varying'],'german-v2.js'),
    ('german_course_enrollments','class_id','OBRIGATORIA',array['uuid','text','character varying'],'german-v2.js'),
    ('german_course_enrollments','candidate_id','OBRIGATORIA',array['text','character varying','uuid'],'german-v2.js'),
    ('german_course_enrollments','status','FUNCIONAL',array[]::text[],'german-v2.js'),
    ('german_course_enrollments','enrolled_at','FUNCIONAL',array['date','timestamp with time zone','timestamp without time zone','text'],'german-v2.js'),
    ('german_course_enrollments','completed_at','FUNCIONAL',array['date','timestamp with time zone','timestamp without time zone','text'],'german-v2.js'),
    ('german_course_enrollments','current_level','FUNCIONAL',array[]::text[],'german-v2.js'),
    ('german_course_enrollments','target_level','FUNCIONAL',array[]::text[],'german-v2.js'),
    ('german_course_enrollments','attendance_percent','FUNCIONAL',array['numeric','integer','text','character varying'],'german-v2.js'),
    ('german_course_enrollments','progress_percent','FUNCIONAL',array['numeric','integer','text','character varying'],'german-v2.js'),
    ('german_course_enrollments','performance','FUNCIONAL',array[]::text[],'german-v2.js'),
    ('german_course_enrollments','risk_level','FUNCIONAL',array[]::text[],'german-v2.js'),
    ('german_course_enrollments','exam_status','FUNCIONAL',array[]::text[],'german-v2.js'),
    ('german_course_enrollments','next_action','FUNCIONAL',array[]::text[],'german-v2.js'),
    ('german_course_enrollments','next_action_due','FUNCIONAL',array['date','timestamp with time zone','timestamp without time zone','text'],'german-v2.js'),
    ('german_course_enrollments','owner_name','FUNCIONAL',array[]::text[],'german-v2.js'),
    ('german_course_enrollments','notes','FUNCIONAL',array[]::text[],'german-v2.js'),
    ('german_course_enrollments','last_assessment_score','FUNCIONAL',array['numeric','integer','text','character varying'],'german-v2.js'),
    ('german_course_enrollments','last_assessment_at','FUNCIONAL',array['date','timestamp with time zone','timestamp without time zone','text'],'german-v2.js'),
    ('german_course_enrollments','created_at','FUNCIONAL',array['timestamp with time zone','timestamp without time zone'],'german-v2.js'),
    ('german_course_enrollments','updated_at','FUNCIONAL',array['timestamp with time zone','timestamp without time zone'],'german-v2.js'),
    ('german_course_updates','id','OBRIGATORIA',array['uuid','text','character varying'],'german-v2.js'),
    ('german_course_updates','enrollment_id','OBRIGATORIA',array['uuid','text','character varying'],'german-v2.js'),
    ('german_course_updates','event_date','FUNCIONAL',array['date','timestamp with time zone','timestamp without time zone','text'],'german-v2.js'),
    ('german_course_updates','kind','FUNCIONAL',array[]::text[],'german-v2.js'),
    ('german_course_updates','attendance_status','FUNCIONAL',array[]::text[],'german-v2.js'),
    ('german_course_updates','score','FUNCIONAL',array['numeric','integer','text','character varying'],'german-v2.js'),
    ('german_course_updates','level_after','FUNCIONAL',array[]::text[],'german-v2.js'),
    ('german_course_updates','note','FUNCIONAL',array[]::text[],'german-v2.js'),

    ('usuarios','username','OBRIGATORIA',array['text','character varying'],'t4-v2-data.js'),
    ('usuarios','nome','FUNCIONAL',array[]::text[],'t4-v2-data.js'),
    ('usuarios','role','OBRIGATORIA',array['text','character varying'],'t4-v2-data.js'),
    ('usuarios','color','FUNCIONAL',array[]::text[],'t4-v2-data.js'),
    ('usuarios','ativo','OBRIGATORIA',array['boolean','text','character varying'],'t4-v2-data.js'),
    ('usuarios','auth_uid','OBRIGATORIA',array['uuid','text','character varying'],'00_preflight.sql/10_additive.sql')
), expected_functions(signature, feature) as (
  values
    ('public.can_edit_crm()', 'Autorização de edição'),
    ('public.current_username_from_auth()', 'Identidade do perfil interno'),
    ('auth.uid()', 'Identidade da sessão')
), table_report as (
  select
    'TABELA'::text as object_type,
    t.table_name::text,
    null::text as column_name,
    t.feature::text,
    case when t.security_expected then 'RLS_OBRIGATORIO' else 'RLS_INFORMATIVO' end::text as criticality,
    case
      when c.oid is null then 'TABELA_AUSENTE'
      when t.security_expected and not c.relrowsecurity then 'RLS_AUSENTE'
      when p.policy_count = 0 then 'SEM_POLITICAS'
      else 'OK'
    end::text as status,
    null::text as data_type,
    null::text as udt_name,
    null::text[] as accepted_types,
    p.policy_count,
    jsonb_build_object(
      'rls', c.relrowsecurity,
      'anon_select', case when c.oid is not null then has_table_privilege('anon', c.oid, 'SELECT') end,
      'authenticated_select', case when c.oid is not null then has_table_privilege('authenticated', c.oid, 'SELECT') end,
      'authenticated_insert', case when c.oid is not null then has_table_privilege('authenticated', c.oid, 'INSERT') end,
      'authenticated_update', case when c.oid is not null then has_table_privilege('authenticated', c.oid, 'UPDATE') end,
      'authenticated_delete', case when c.oid is not null then has_table_privilege('authenticated', c.oid, 'DELETE') end
    ) as privileges,
    'pg_class + pg_policies'::text as source
  from expected_tables t
  left join pg_class c on c.oid = to_regclass('public.' || t.table_name)
  left join lateral (
    select count(*)::bigint as policy_count
    from pg_policies p
    where p.schemaname = 'public' and p.tablename = t.table_name
  ) p on true
), column_report as (
  select
    'COLUNA'::text as object_type,
    e.table_name::text,
    e.column_name::text,
    t.feature::text,
    e.criticality::text,
    case
      when c.column_name is null and e.criticality = 'OBRIGATORIA' then 'COLUNA_AUSENTE_OBRIGATORIA'
      when c.column_name is null then 'COLUNA_AUSENTE_FUNCIONAL'
      when cardinality(e.accepted_types) > 0 and not c.data_type = any(e.accepted_types) then 'TIPO_DIVERGENTE'
      else 'OK'
    end::text as status,
    c.data_type::text,
    c.udt_name::text,
    e.accepted_types,
    null::bigint as policy_count,
    null::jsonb as privileges,
    e.source::text
  from expected_columns e
  join expected_tables t on t.table_name = e.table_name
  left join information_schema.columns c
    on c.table_schema = 'public'
   and c.table_name = e.table_name
   and c.column_name = e.column_name
), function_report as (
  select
    'FUNCAO'::text as object_type,
    'public/auth'::text as table_name,
    f.signature::text as column_name,
    f.feature::text,
    'OBRIGATORIA'::text as criticality,
    case when p.oid is null then 'FUNCAO_AUSENTE' else 'OK' end::text as status,
    null::text as data_type,
    null::text as udt_name,
    null::text[] as accepted_types,
    null::bigint as policy_count,
    null::jsonb as privileges,
    'pg_proc'::text as source
  from expected_functions f
  left join pg_proc p on p.oid = to_regprocedure(f.signature)
), report as (
  select * from table_report
  union all select * from column_report
  union all select * from function_report
)
select object_type, table_name, column_name, feature, criticality, status,
       data_type, udt_name, accepted_types, policy_count, privileges, source
from report
order by
  case when status in ('TABELA_AUSENTE','RLS_AUSENTE','SEM_POLITICAS','COLUNA_AUSENTE_OBRIGATORIA','TIPO_DIVERGENTE','FUNCAO_AUSENTE') then 0 else 1 end,
  object_type, table_name, column_name;
